#!/usr/bin/env bash
ARGS="$@"

outargs=""
outfile=""
nb=""

while [[ $# -gt 0 ]]
do
key="$1"

case $key in

    -outfile)
    outfile="$2"
    shift
    shift
    ;;

    -n)
    nb="$2"
    shift
    shift
    ;;

    *)
    shift
    ;;

esac
done

parallelPaths -j $outargs $nb $outfile
